import { CompanyTypeValue, EntityEnding, Industry, NationPhone, NationValue } from "../api/types";
import { OptionInfo } from "../types/common";

export const NATION_INFOS: OptionInfo<NationValue>[] = [
  {value: 'CA',	label: 'Canada'},
  {value: 'US',	label: 'United States'},
  {value: 'RO',	label: 'Russia'},
  {value: 'EG',	label: 'Egypt'},
  {value: 'ZA',	label: 'South Africa'},
  {value: 'GR',	label: 'Greece'},
  {value: 'NL',	label: 'Netherlands'},
  {value: 'BE',	label: 'Belgium'},
  {value: 'FR',	label: 'France'},
  {value: 'ES',	label: 'Spain'},
  {value: 'HU',	label: 'Hungary'},
  {value: 'IT',	label: 'Italy'},
  {value: 'RO',	label: 'Romania'},
  {value: 'CH',	label: 'Switzerland'},
  {value: 'AT',	label: 'Austria'},
  {value: 'GB',	label: 'United Kingdom'},
  {value: 'DK',	label: 'Denmark'},
  {value: 'SE',	label: 'Sweden'},
  {value: 'NO',	label: 'Norway'},
  {value: 'PL',	label: 'Poland'},
  {value: 'DE',	label: 'Germany'},
  {value: 'PE',	label: 'Peru'},
  {value: 'MX',	label: 'Mexico'},
  {value: 'CU',	label: 'Cuba'},
  {value: 'AR',	label: 'Argentina'},
  {value: 'BR',	label: 'Brazil'},
  {value: 'CL',	label: 'Chile'},
  {value: 'CO',	label: 'Colombia'},
  {value: 'VE',	label: 'Venezuela'},
  {value: 'MY',	label: 'Malaysia'},
  {value: 'AU',	label: 'Australia'},
  {value: 'ID',	label: 'Indonesia'},
  {value: 'PH',	label: 'Philippines'},
  {value: 'NZ',	label: 'New Zealand'},
  {value: 'SG',	label: 'Singapore'},
  {value: 'TZ',	label: 'Thái Lan'},
  {value: 'KZ', label: 'Kazakhstan'},
  {value: 'KZ',	label: 'Kazakhstan'},
  {value: 'JP',	label: 'Japan'},
  {value: 'HT',	label: 'Hàn Quốc'},
  {value: 'VN',	label: 'Vietnam'},
  {value: 'CN',	label: 'China'},
  {value: 'TR',	label: 'Turkey'},
  {value: 'IN',	label: 'India'},
  {value: 'PK',	label: 'Pakistan'},
  {value: 'AF',	label: 'Afghanistan'},
  {value: 'LK',	label: 'Sri Lanka'},
  {value: 'MM',	label: 'Myanmar'},
  {value: 'ID',	label: 'Iran'},
  {value: 'MA',	label: 'Morocco'},
  {value: 'DZ',	label: 'Algeria'},
  {value: 'TN',	label: 'Tunisia'},
  {value: 'LR',	label: 'Libya'},
  {value: 'GM',	label: 'Gambia'},
  {value: 'SN',	label: 'Senegal'},
  {value: 'MR',	label: 'Mauritania'},
  {value: 'ML',	label: 'Mali'},
  {value: 'GN',	label: 'Guinea'},
  {value: 'CI',	label: 'Côte d’lvoire'},
  {value: 'IT',	label: 'Ivory Coast'},
  {value: 'BF',	label: 'Burkina Faso'},
  {value: 'NE',	label: 'Niger Republic'},
  {value: 'TG',	label: 'Togo'},
  {value: 'BJ',	label: 'Benin'},
  {value: 'MU',	label: 'Mauritius'},
  {value: 'LR',	label: 'Liberia'},
  {value: 'SL',	label: 'Sierra Leone'},
  {value: 'GH',	label: 'Ghana'},
  {value: 'NG',	label: 'Nigeria'},
  {value: 'TD',	label: 'Chad'},
  {value: 'CF',	label: 'Central African Republic'},
  {value: 'CM',	label: 'Cameroon'},
  {value: 'CV',	label: 'Cape Verde'},
  {value: 'SY',	label: 'Sใo Tom้ & Principe'},
  {value: 'GQ',	label: 'Equatorial Guinea'},
  {value: 'GA',	label: 'Gabon'},
  {value: 'CG',	label: 'Congo'},
  {value: 'BS',	label: 'Bahamas'},
  {value: 'CG',	label: 'Congo, Dem. Rep. of'},
  {value: 'YE',	label: 'Zaire'},
  {value: 'AO',	label: 'Angola'},
  {value: 'GW',	label: 'Guinea-Bissau'},
  {value: 'TD',	label: 'Chagos Archipelago'},
  {value: 'BB',	label: 'Barbados'},
  {value: 'SC',	label: 'Seychelles'},
  {value: 'SD',	label: 'Sudan'},
  {value: 'RW',	label: 'Rwanda'},
  {value: 'ET',	label: 'Ethiopia'},
  {value: 'SO',	label: 'Somalia'},
  {value: 'DJ',	label: 'Djibouti'},
  {value: 'KE',	label: 'Kenya'},
  {value: 'TJ',	label: 'Tanzania'},
  {value: 'UG',	label: 'Uganda'},
  {value: 'BI',	label: 'Burundi'},
  {value: 'MZ',	label: 'Mozambique'},
  {value: 'ZM',	label: 'Zambia'},
  {value: 'MG',	label: 'Madagascar'},
  {value: 'RE',	label: 'Reunion Island'},
  {value: 'ZW',	label: 'Zimbabwe'},
  {value: 'NA',	label: 'Namibia'},
  {value: 'MW',	label: 'Malawi'},
  {value: 'LS',	label: 'Lesotho'},
  {value: 'BW',	label: 'Botswana'},
  {value: 'SZ',	label: 'Swaziland'},
  {value: 'KM',	label: 'Comoros'},
  {value: 'AW',	label: 'Aruba'},
  {value: 'ET',	label: 'Faeroe Islands'},
  {value: 'GL',	label: 'Greenland'},
  {value: 'GI',	label: 'Gibraltar'},
  {value: 'PT',	label: 'Portugal'},
  {value: 'LU',	label: 'Luxembourg'},
  {value: 'IE',	label: 'Ireland'},
  {value: 'IS',	label: 'Iceland'},
  {value: 'AL',	label: 'Albania'},
  {value: 'MT',	label: 'Malta'},
  {value: 'CY',	label: 'Cyprus'},
  {value: 'FI',	label: 'Finland'},
  {value: 'BG',	label: 'Bulgaria'},
  {value: 'LT',	label: 'Lithuania'},
  {value: 'LV',	label: 'Latvia'},
  {value: 'EE',	label: 'Estonia'},
  {value: 'FM',	label: 'Moldova'},
  {value: 'AM',	label: 'Armenia'},
  {value: 'BY',	label: 'Belarus'},
  {value: 'AD',	label: 'Andorra'},
  {value: 'MC',	label: 'Monaco'},
  {value: 'SM',	label: 'San Marino'},
  {value: 'UA',	label: 'Ukraine'},
  {value: 'MN',	label: 'Montenegro & Serbia'},
  {value: 'YE',	label: 'Yugoslavia'},
  {value: 'HR',	label: 'Croatia'},
  {value: 'SI',	label: 'Slovenia'},
  {value: 'BO',	label: 'Bosnia & Herzegovina'},
  {value: 'MO',	label: 'Macedonia'},
  {value: 'CZ',	label: 'Czech Republic'},
  {value: 'SG',	label: 'Slovak Republic'},
  {value: 'LI',	label: 'Liechtenstein'},
  {value: 'BM',	label: 'Bermuda'},
  {value: 'ET',	label: 'Falkland Islands'},
  {value: 'BZ',	label: 'Belize'},
  {value: 'GT',	label: 'Guatemala'},
  {value: 'SV',	label: 'El Salvador'},
  {value: 'HN',	label: 'Honduras'},
  {value: 'NI',	label: 'Nicaragua'},
  {value: 'CR',	label: 'Costa Rica'},
  {value: 'PA',	label: 'Panama'},
  {value: 'HT',	label: 'Haiti'},
  {value: 'GP',	label: 'Guadeloupe'},
  {value: 'BO',	label: 'Bolivia'},
  {value: 'GY',	label: 'Guyana'},
  {value: 'EC',	label: 'Ecuador'},
  {value: 'GF',	label: 'French Guiana'},
  {value: 'PY',	label: 'Paraguay'},
  {value: 'FR',	label: 'French Antilles'},
  {value: 'MQ',	label: 'Martinique'},
  {value: 'SR',	label: 'Suriname'},
  {value: 'UY',	label: 'Uruguay'},
  {value: 'AN',	label: 'Netherlands Antilles'},
  {value: 'BN',	label: 'Brunei Darussalam'},
  {value: 'PG',	label: 'Papua New Guinea'},
  {value: 'TO',	label: 'Tonga'},
  {value: 'SB',	label: 'Solomon Islands'},
  {value: 'VU',	label: 'Vanuatu'},
  {value: 'FJ',	label: 'Fiji'},
  {value: 'PW',	label: 'Palau'},
  {value: 'CK',	label: 'Cook Islands'},
  {value: 'AS',	label: 'American Samoa'},
  {value: 'EH',	label: 'Western Samoa'},
  {value: 'NC',	label: 'New Caledonia'},
  {value: 'TV',	label: 'Tuvalu'},
  {value: 'PF',	label: 'French Polynesia'},
  {value: 'MH',	label: 'Marshall Islands'},
  {value: 'FM',	label: 'Midway Islands'},
  {value: 'TO',	label: 'Triều Tiên'},
  {value: 'HK',	label: 'Hong Kong'},
  {value: 'MO',	label: 'Macau'},
  {value: 'KH',	label: 'Cambodia'},
  {value: 'LA',	label: 'Laos'},
  {value: 'BD',	label: 'Bangladesh'},
  {value: 'SY',	label: 'Taiwan'},
  {value: 'MV',	label: 'Maldives'},
  {value: 'LB',	label: 'Lebanon'},
  {value: 'JO',	label: 'Jordan'},
  {value: 'CH',	label: 'Syria'},
  {value: 'IQ',	label: 'Iraq'},
  {value: 'KW',	label: 'Kuwait'},
  {value: 'SA',	label: 'Saudi Arabia'},
  {value: 'YE',	label: 'Yemen'},
  {value: 'OM',	label: 'Oman'},
  {value: 'AE',	label: 'United Arab Emirates'},
  {value: 'IL',	label: 'Israel'},
  {value: 'BH',	label: 'Bahrain'},
  {value: 'QA',	label: 'Qatar'},
  {value: 'BT',	label: 'Bhutan'},
  {value: 'MN',	label: 'Mongolia'},
  {value: 'NP',	label: 'Nepal'},
  {value: 'TJ',	label: 'Tajikistan'},
  {value: 'TM',	label: 'Turkmenistan'},
  {value: 'AZ',	label: 'Azerbaijan'},
  {value: 'GE',	label: 'Georgia'},
  {value: 'KG',	label: 'Kyrgyzstan'},
  {value: 'UZ',	label: 'Uzbekistan'},
  {value: 'AI',	label: 'Anguilla'},
  {value: 'AQ',	label: 'Antigua & Barbuda'},
  {value: 'VG',	label: 'Virgin Islands, British'},
  {value: 'VI',	label: 'Virgin Islands, U.S'},
  {value: 'KY',	label: 'Cayman Islands'},
  {value: 'GD',	label: 'Grenada'},
  {value: 'TM',	label: 'Turks & Caicos Islands'},
  {value: 'MS',	label: 'Montserrat'},
  {value: 'NF',	label: 'Northern Mariana Isl'},
  {value: 'GU',	label: 'Guam'},
  {value: 'LK',	label: 'St. Lucia'},
  {value: 'DM',	label: 'Dominica'},
  {value: 'LK',	label: 'St. Vincents & Grenadines'},
  {value: 'PR',	label: 'Puerto Rico'},
  {value: 'DO',	label: 'Dominican Republic'},
  {value: 'TO',	label: 'Trinidad & Tobago'},
  {value: 'LK',	label: 'St. Kitts & Nevis'},
  {value: 'JM',	label: 'Jamaica'},
].sort((v1, v2) => v1.value.localeCompare(v2.value))

export const NATION_PHONE_INFOS: OptionInfo<NationPhone>[] = [
  {value: '+1',	label: '+1'	, iconElement: <div>CA</div>},
  {value: '+1',	label: '+1'	, iconElement: <div>US</div>},
  {value: '+7',	label: '+7'	, iconElement: <div>RO</div>},
  {value: '+20',	label: '+20'	, iconElement: <div>EG</div>},
  {value: '+27',	label: '+27'	, iconElement: <div>ZA</div>},
  {value: '+30',	label: '+30'	, iconElement: <div>GR</div>},
  {value: '+31',	label: '+31'	, iconElement: <div>NL</div>},
  {value: '+32',	label: '+32'	, iconElement: <div>BE</div>},
  {value: '+33',	label: '+33'	, iconElement: <div>FR</div>},
  {value: '+34',	label: '+34'	, iconElement: <div>ES</div>},
  {value: '+36',	label: '+36'	, iconElement: <div>HU</div>},
  {value: '+39',	label: '+39'	, iconElement: <div>IT</div>},
  {value: '+40',	label: '+40'	, iconElement: <div>RO</div>},
  {value: '+41',	label: '+41'	, iconElement: <div>CH</div>},
  {value: '+43',	label: '+43'	, iconElement: <div>AT</div>},
  {value: '+44',	label: '+44'	, iconElement: <div>GB</div>},
  {value: '+45',	label: '+45'	, iconElement: <div>DK</div>},
  {value: '+46',	label: '+46'	, iconElement: <div>SE</div>},
  {value: '+47',	label: '+47'	, iconElement: <div>NO</div>},
  {value: '+48',	label: '+48'	, iconElement: <div>PL</div>},
  {value: '+49',	label: '+49'	, iconElement: <div>DE</div>},
  {value: '+51',	label: '+51'	, iconElement: <div>PE</div>},
  {value: '+52',	label: '+52'	, iconElement: <div>MX</div>},
  {value: '+53',	label: '+53'	, iconElement: <div>CU</div>},
  {value: '+54',	label: '+54'	, iconElement: <div>AR</div>},
  {value: '+55',	label: '+55'	, iconElement: <div>BR</div>},
  {value: '+56',	label: '+56'	, iconElement: <div>CL</div>},
  {value: '+57',	label: '+57'	, iconElement: <div>CO</div>},
  {value: '+58',	label: '+58'	, iconElement: <div>VE</div>},
  {value: '+60',	label: '+60'	, iconElement: <div>MY</div>},
  {value: '+61',	label: '+61'	, iconElement: <div>AU</div>},
  {value: '+62',	label: '+62'	, iconElement: <div>ID</div>},
  {value: '+63',	label: '+63'	, iconElement: <div>PH</div>},
  {value: '+64',	label: '+64'	, iconElement: <div>NZ</div>},
  {value: '+65',	label: '+65'	, iconElement: <div>SG</div>},
  {value: '+66',	label: '+66'	, iconElement: <div>TZ</div>},
  {value: '+76', label: '+76'	, iconElement: <div>KZ</div>},
  {value: '+77',	label: '+77'	, iconElement: <div>KZ</div>},
  {value: '+81',	label: '+81'	, iconElement: <div>JP</div>},
  {value: '+82',	label: '+82'	, iconElement: <div>HT</div>},
  {value: '+84',	label: '+84'	, iconElement: <div>VN</div>},
  {value: '+86',	label: '+86'	, iconElement: <div>CN</div>},
  {value: '+90',	label: '+90'	, iconElement: <div>TR</div>},
  {value: '+91',	label: '+91'	, iconElement: <div>IN</div>},
  {value: '+92',	label: '+92'	, iconElement: <div>PK</div>},
  {value: '+93',	label: '+93'	, iconElement: <div>AF</div>},
  {value: '+94',	label: '+94'	, iconElement: <div>LK</div>},
  {value: '+95',	label: '+95'	, iconElement: <div>MM</div>},
  {value: '+98',	label: '+98'	, iconElement: <div>ID</div>},
  {value: '+212',	label: '+212'	, iconElement: <div>MA</div>},
  {value: '+213',	label: '+213'	, iconElement: <div>DZ</div>},
  {value: '+216',	label: '+216'	, iconElement: <div>TN</div>},
  {value: '+218',	label: '+218'	, iconElement: <div>LR</div>},
  {value: '+220',	label: '+220'	, iconElement: <div>GM</div>},
  {value: '+221',	label: '+221'	, iconElement: <div>SN</div>},
  {value: '+222',	label: '+222'	, iconElement: <div>MR</div>},
  {value: '+223',	label: '+223'	, iconElement: <div>ML</div>},
  {value: '+224',	label: '+224'	, iconElement: <div>GN</div>},
  {value: '+225',	label: '+225'	, iconElement: <div>CI</div>},
  {value: '+225',	label: '+225'	, iconElement: <div>IT</div>},
  {value: '+226',	label: '+226'	, iconElement: <div>BF</div>},
  {value: '+227',	label: '+227'	, iconElement: <div>NE</div>},
  {value: '+228',	label: '+228'	, iconElement: <div>TG</div>},
  {value: '+229',	label: '+229'	, iconElement: <div>BJ</div>},
  {value: '+230',	label: '+230'	, iconElement: <div>MU</div>},
  {value: '+231',	label: '+231'	, iconElement: <div>LR</div>},
  {value: '+232',	label: '+232'	, iconElement: <div>SL</div>},
  {value: '+233',	label: '+233'	, iconElement: <div>GH</div>},
  {value: '+234',	label: '+234'	, iconElement: <div>NG</div>},
  {value: '+235',	label: '+235'	, iconElement: <div>TD</div>},
  {value: '+236',	label: '+236'	, iconElement: <div>CF</div>},
  {value: '+237',	label: '+237'	, iconElement: <div>CM</div>},
  {value: '+238',	label: '+238'	, iconElement: <div>CV</div>},
  {value: '+239',	label: '+239'	, iconElement: <div>SY</div>},
  {value: '+240',	label: '+240'	, iconElement: <div>GQ</div>},
  {value: '+241',	label: '+241'	, iconElement: <div>GA</div>},
  {value: '+242',	label: '+242'	, iconElement: <div>CG</div>},
  {value: '+243',	label: '+243'	, iconElement: <div>BS</div>},
  {value: '+243',	label: '+243'	, iconElement: <div>CG</div>},
  {value: '+243',	label: '+243'	, iconElement: <div>YE</div>},
  {value: '+244',	label: '+244'	, iconElement: <div>AO</div>},
  {value: '+245',	label: '+245'	, iconElement: <div>GW</div>},
  {value: '+246',	label: '+246'	, iconElement: <div>TD</div>},
  {value: '+247',	label: '+247'	, iconElement: <div>BB</div>},
  {value: '+248',	label: '+248'	, iconElement: <div>SC</div>},
  {value: '+249',	label: '+249'	, iconElement: <div>SD</div>},
  {value: '+250',	label: '+250'	, iconElement: <div>RW</div>},
  {value: '+251',	label: '+251'	, iconElement: <div>ET</div>},
  {value: '+252',	label: '+252'	, iconElement: <div>SO</div>},
  {value: '+253',	label: '+253'	, iconElement: <div>DJ</div>},
  {value: '+254',	label: '+254'	, iconElement: <div>KE</div>},
  {value: '+255',	label: '+255'	, iconElement: <div>TJ</div>},
  {value: '+256',	label: '+256'	, iconElement: <div>UG</div>},
  {value: '+257',	label: '+257'	, iconElement: <div>BI</div>},
  {value: '+258',	label: '+258'	, iconElement: <div>MZ</div>},
  {value: '+260',	label: '+260'	, iconElement: <div>ZM</div>},
  {value: '+261',	label: '+261'	, iconElement: <div>MG</div>},
  {value: '+262',	label: '+262'	, iconElement: <div>RE</div>},
  {value: '+263',	label: '+263'	, iconElement: <div>ZW</div>},
  {value: '+264',	label: '+264'	, iconElement: <div>NA</div>},
  {value: '+265',	label: '+265'	, iconElement: <div>MW</div>},
  {value: '+266',	label: '+266'	, iconElement: <div>LS</div>},
  {value: '+267',	label: '+267'	, iconElement: <div>BW</div>},
  {value: '+268',	label: '+268'	, iconElement: <div>SZ</div>},
  {value: '+269',	label: '+269'	, iconElement: <div>KM</div>},
  {value: '+297',	label: '+297'	, iconElement: <div>AW</div>},
  {value: '+298',	label: '+298'	, iconElement: <div>ET</div>},
  {value: '+299',	label: '+299'	, iconElement: <div>GL</div>},
  {value: '+350',	label: '+350'	, iconElement: <div>GI</div>},
  {value: '+351',	label: '+351'	, iconElement: <div>PT</div>},
  {value: '+352',	label: '+352'	, iconElement: <div>LU</div>},
  {value: '+353',	label: '+353'	, iconElement: <div>IE</div>},
  {value: '+354',	label: '+354'	, iconElement: <div>IS</div>},
  {value: '+355',	label: '+355'	, iconElement: <div>AL</div>},
  {value: '+356',	label: '+356'	, iconElement: <div>MT</div>},
  {value: '+357',	label: '+357'	, iconElement: <div>CY</div>},
  {value: '+358',	label: '+358'	, iconElement: <div>FI</div>},
  {value: '+359',	label: '+359'	, iconElement: <div>BG</div>},
  {value: '+370',	label: '+370'	, iconElement: <div>LT</div>},
  {value: '+371',	label: '+371'	, iconElement: <div>LV</div>},
  {value: '+372',	label: '+372'	, iconElement: <div>EE</div>},
  {value: '+373',	label: '+373'	, iconElement: <div>FM</div>},
  {value: '+374',	label: '+374'	, iconElement: <div>AM</div>},
  {value: '+375',	label: '+375'	, iconElement: <div>BY</div>},
  {value: '+376',	label: '+376'	, iconElement: <div>AD</div>},
  {value: '+377',	label: '+377'	, iconElement: <div>MC</div>},
  {value: '+378',	label: '+378'	, iconElement: <div>SM</div>},
  {value: '+380',	label: '+380'	, iconElement: <div>UA</div>},
  {value: '+381',	label: '+381'	, iconElement: <div>MN</div>},
  {value: '+381',	label: '+381'	, iconElement: <div>YE</div>},
  {value: '+385',	label: '+385'	, iconElement: <div>HR</div>},
  {value: '+386',	label: '+386'	, iconElement: <div>SI</div>},
  {value: '+387',	label: '+387'	, iconElement: <div>BO</div>},
  {value: '+389',	label: '+389'	, iconElement: <div>MO</div>},
  {value: '+420',	label: '+420'	, iconElement: <div>CZ</div>},
  {value: '+421',	label: '+421'	, iconElement: <div>SG</div>},
  {value: '+423',	label: '+423'	, iconElement: <div>LI</div>},
  {value: '+442',	label: '+442'	, iconElement: <div>BM</div>},
  {value: '+500',	label: '+500'	, iconElement: <div>ET</div>},
  {value: '+501',	label: '+501'	, iconElement: <div>BZ</div>},
  {value: '+502',	label: '+502'	, iconElement: <div>GT</div>},
  {value: '+503',	label: '+503'	, iconElement: <div>SV</div>},
  {value: '+504',	label: '+504'	, iconElement: <div>HN</div>},
  {value: '+505',	label: '+505'	, iconElement: <div>NI</div>},
  {value: '+506',	label: '+506'	, iconElement: <div>CR</div>},
  {value: '+507',	label: '+507'	, iconElement: <div>PA</div>},
  {value: '+509',	label: '+509'	, iconElement: <div>HT</div>},
  {value: '+590',	label: '+590'	, iconElement: <div>GP</div>},
  {value: '+591',	label: '+591'	, iconElement: <div>BO</div>},
  {value: '+592',	label: '+592'	, iconElement: <div>GY</div>},
  {value: '+593',	label: '+593'	, iconElement: <div>EC</div>},
  {value: '+594',	label: '+594'	, iconElement: <div>GF</div>},
  {value: '+595',	label: '+595'	, iconElement: <div>PY</div>},
  {value: '+596',	label: '+596'	, iconElement: <div>FR</div>},
  {value: '+596',	label: '+596'	, iconElement: <div>MQ</div>},
  {value: '+597',	label: '+597'	, iconElement: <div>SR</div>},
  {value: '+598',	label: '+598'	, iconElement: <div>UY</div>},
  {value: '+599',	label: '+599'	, iconElement: <div>AN</div>},
  {value: '+673',	label: '+673'	, iconElement: <div>BN</div>},
  {value: '+675',	label: '+675'	, iconElement: <div>PG</div>},
  {value: '+676',	label: '+676'	, iconElement: <div>TO</div>},
  {value: '+677',	label: '+677'	, iconElement: <div>SB</div>},
  {value: '+678',	label: '+678'	, iconElement: <div>VU</div>},
  {value: '+679',	label: '+679'	, iconElement: <div>FJ</div>},
  {value: '+680',	label: '+680'	, iconElement: <div>PW</div>},
  {value: '+682',	label: '+682'	, iconElement: <div>CK</div>},
  {value: '+684',	label: '+684'	, iconElement: <div>AS</div>},
  {value: '+685',	label: '+685'	, iconElement: <div>EH</div>},
  {value: '+687',	label: '+687'	, iconElement: <div>NC</div>},
  {value: '+688',	label: '+688'	, iconElement: <div>TV</div>},
  {value: '+689',	label: '+689'	, iconElement: <div>PF</div>},
  {value: '+692',	label: '+692'	, iconElement: <div>MH</div>},
  {value: '+808',	label: '+808'	, iconElement: <div>FM</div>},
  {value: '+850',	label: '+850'	, iconElement: <div>TO</div>},
  {value: '+852',	label: '+852'	, iconElement: <div>HK</div>},
  {value: '+853',	label: '+853'	, iconElement: <div>MO</div>},
  {value: '+855',	label: '+855'	, iconElement: <div>KH</div>},
  {value: '+856',	label: '+856'	, iconElement: <div>LA</div>},
  {value: '+880',	label: '+880'	, iconElement: <div>BD</div>},
  {value: '+886',	label: '+886'	, iconElement: <div>SY</div>},
  {value: '+960',	label: '+960'	, iconElement: <div>MV</div>},
  {value: '+961',	label: '+961'	, iconElement: <div>LB</div>},
  {value: '+962',	label: '+962'	, iconElement: <div>JO</div>},
  {value: '+963',	label: '+963'	, iconElement: <div>CH</div>},
  {value: '+964',	label: '+964'	, iconElement: <div>IQ</div>},
  {value: '+965',	label: '+965'	, iconElement: <div>KW</div>},
  {value: '+966',	label: '+966'	, iconElement: <div>SA</div>},
  {value: '+967',	label: '+967'	, iconElement: <div>YE</div>},
  {value: '+968',	label: '+968'	, iconElement: <div>OM</div>},
  {value: '+971',	label: '+971'	, iconElement: <div>AE</div>},
  {value: '+972',	label: '+972'	, iconElement: <div>IL</div>},
  {value: '+973',	label: '+973'	, iconElement: <div>BH</div>},
  {value: '+974',	label: '+974'	, iconElement: <div>QA</div>},
  {value: '+975',	label: '+975'	, iconElement: <div>BT</div>},
  {value: '+976',	label: '+976'	, iconElement: <div>MN</div>},
  {value: '+977',	label: '+977'	, iconElement: <div>NP</div>},
  {value: '+992',	label: '+992'	, iconElement: <div>TJ</div>},
  {value: '+993',	label: '+993'	, iconElement: <div>TM</div>},
  {value: '+994',	label: '+994'	, iconElement: <div>AZ</div>},
  {value: '+995',	label: '+995'	, iconElement: <div>GE</div>},
  {value: '+996',	label: '+996'	, iconElement: <div>KG</div>},
  {value: '+998',	label: '+998'	, iconElement: <div>UZ</div>},
  {value: '+1264',	label: '+1264'	, iconElement: <div>AI</div>},
  {value: '+1268',	label: '+1268'	, iconElement: <div>AQ</div>},
  {value: '+1284',	label: '+1284'	, iconElement: <div>VG</div>},
  {value: '+1340',	label: '+1340' , iconElement: <div>VI</div>},
  {value: '+1345',	label: '+1345'	, iconElement: <div>KY</div>},
  {value: '+1473',	label: '+1473'	, iconElement: <div>GD</div>},
  {value: '+1649',	label: '+1649'	, iconElement: <div>TM</div>},
  {value: '+1664',	label: '+1664'	, iconElement: <div>MS</div>},
  {value: '+1670',	label: '+1670' , iconElement: <div>NF</div>},
  {value: '+1671',	label: '+1671'	, iconElement: <div>GU</div>},
  {value: '+1758',	label: '+1758'	, iconElement: <div>LK</div>},
  {value: '+1767',	label: '+1767'	, iconElement: <div>DM</div>},
  {value: '+1784',	label: '+1784'	, iconElement: <div>LK</div>},
  {value: '+1787',	label: '+1787'	, iconElement: <div>PR</div>},
  {value: '+1809',	label: '+1809'	, iconElement: <div>DO</div>},
  {value: '+1868',	label: '+1868'	, iconElement: <div>TO</div>},
  {value: '+1869',	label: '+1869'	, iconElement: <div>LK</div>},
  {value: '+1876',	label: '+1876'	, iconElement: <div>JM</div>},
]

export const COMPANY_TYPE_INFOS: OptionInfo<CompanyTypeValue>[] = [
  {value: 'LLC', label: 'LLC (Limited Liability Company)'},
  {value: 'PLC', label: 'PLC (Private Limited Company)'},
]

export const ENTITY_ENDING_INFOS: OptionInfo<EntityEnding>[] = [
  {value: 'LLC', label: 'LLC'},
  {value: 'L.L.C', label: 'L.L.C'},
  {value: 'LIMITED LIABILITY COMPANY', label: 'LIMITED LIABILITY COMPANY'},
  {value: 'PRIVATE LIMITED COMPANY', label: 'PRIVATE LIMITED COMPANY'},
]

export const INDUSTRY_INFOS: OptionInfo<Industry>[] = [
  {value: 'Accounting and tax preparation', label: 'Accounting and tax preparation'},
  {value: 'Advertising', label: 'Advertising'},
  {value: 'Agriculture', label: 'Agriculture'},
  {value: 'Art and photography', label: 'Art and photography'},
  {value: 'Artificial intelligence', label: 'Artificial intelligence'},
  {value: 'Augmented reality', label: 'Augmented reality'},
  {value: 'B2B', label: 'B2B'},
  {value: 'Biotech', label: 'Biotech'},
  {value: 'Community', label: 'Community'},
  {value: 'Construction', label: 'Construction'},
  {value: 'Consulting', label: 'Consulting'},
  {value: 'Consumer', label: 'Consumer'},
  {value: 'Crypto', label: 'Crypto'},
  {value: 'Developer tools', label: 'Developer tools'},
  {value: 'Drones', label: 'Drones'},
  {value: 'Online retailer', label: 'Online retailer'},
  {value: 'Education', label: 'Education'},
  {value: 'Energy', label: 'Energy'},
  {value: 'Enterprise', label: 'Enterprise'},
  {value: 'Entertainment', label: 'Entertainment'},
  {value: 'Financial services', label: 'Financial services'},
  {value: 'Other health and fitness services', label: 'Other health and fitness services'},
  {value: 'Other food services', label: 'Other food services'},
  {value: 'Government', label: 'Government'},
  {value: 'Hardware', label: 'Hardware'},
  {value: 'Health services', label: 'Health services'},
  {value: 'Healthcare', label: 'Healthcare'},
  {value: 'Insurance', label: 'Insurance'},
  {value: 'Private investment companies', label: 'Private investment companies'},
  {value: 'Legal services including law', label: 'Legal services including law'},
  {value: 'Firms marketing', label: 'Firms marketing'},
  {value: 'Marketplace', label: 'Marketplace'},
  {value: 'Media', label: 'Media'},
  {value: 'Nonprofit', label: 'Nonprofit'},
  {value: 'Other', label: 'Other'},
  {value: 'Real estate', label: 'Real estate'},
  {value: 'Employment services', label: 'Employment services'},
  {value: 'Research', label: 'Research'},
  {value: 'Robotics', label: 'Robotics'},
  {value: 'Security', label: 'Security'},
  {value: 'Sports teams and clubs', label: 'Sports teams and clubs'},
  {value: 'Transportation', label: 'Transportation'},
  {value: 'Other travel services', label: 'Other travel services'},
  {value: 'Virtual reality', label: 'Virtual reality'},
]

